### ISSUE TITLE
Opening tmControl from Plugin menu gives an error about recursion limit

### ISSUE THREAD

**Issue by matthiasrebbe** [macMikey/tmControl#1]
When tmControl2 is opened from the Plugin menu there is an error about recursion limit
see attached screenshot
![2022-01-27_12-27-40](https://user-images.githubusercontent.com/9978143/151350277-4b8e381c-a5de-49d5-8763-dcd321c11f86.png)

**Comment by macMikey** [comment]
Is that the version that Scott had uploaded on his site or the one in this repo?
Scott's version had some old typos that are fixed in the repo.

**Comment by matthiasrebbe** [comment]
The tm2control plugin has the modification date  27.01.22 1:38am. I removed now both that file and the resources folder and copied again the resources folder and the tm2control file  from your repo to the plugin folder. The described error does not happen anymore.

But another one.
When i press on LAZR2 right after tmControl2 has loaded the themes i get the following error.
![2022-01-27_15-43-43](https://user-images.githubusercontent.com/9978143/151381725-8a2708df-7ed3-4941-9dc7-c5a4bc2b55a5.png)

When i then switch back to themes list and press one of the themes above LAZR2 no error messages comes up. If i then go back to themes liste and press on LAZR2, the error comes up again. 
When  i go back to themes list and scroll down to the end of the list and press on LAZR3 (again no error) and go back to themes list and press LAZR2 again, then no error message comes up and i do not get the error message again until i restart LC and try the steps again.
